#!/usr/bin/env python3
# This file is placed in the Public Domain.


"build"


import os
import sys


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.strip())
        sys.stdout.flush()

popen("python3 setup.py sdist")
popen("python3 -m pip wheel -e .")
popen("mv *.whl dist")