#!/usr/bin/env python3
# This file is placed in the Public Domain.


"lint"


import os
import sys


SKIP = ["---", "Your code"]


def doskip(txt):
    if not txt.strip():
        return True
    for skp in SKIP:
        if skp in txt:
            return True
    return False


def loop(path, txt):
    for fnn in os.listdir(path):
        if not os.path.isdir(fnn):
            continue
        if not os.path.exists("%s/__init__.py" % fnn):
            continue
        os.chdir(fnn)
        for line in os.popen(txt).readlines():
            if doskip(line):
                continue
            print(line.rstrip())
            sys.stdout.flush()
        os.chdir("..")


if __name__ == "__main__":
    os.popen("fin/clean").readlines()
    loop(os.getcwd(), "pylint *")
