#!/usr/bin/env python3
# This file is placed in the Public Domain.


"loop"


import os
import sys


SKIP = ["env"]

def loop(path, txt):
    for fnn in os.listdir(path):
        if not os.path.isdir(fnn):
            continue
        if fnn in SKIP:
            continue
        os.chdir(fnn)
        popen(txt)
        os.chdir("..")


def popen(txt):
    for line in os.popen(txt).readlines():
        print(line.rstrip())
        sys.stdout.flush()


if __name__ == "__main__":
    if not len(sys.argv) >= 3:
        print("loop <dir> <cmd>")
    else:
        loop(sys.argv[1], " ".join(sys.argv[2:]))
